#!/bin/sh

echo "Checking for homebrew..."
if ! command -v brew >/dev/null; then
  echo "Installing homebrew..."

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Updating homebrew..."
brew update

echo "Installing/Updating brew/cask applications..."
brew bundle --file=- <<EOF
  # Taps
  tap "caskroom/cask"

  # Casks
  cask "spectacle"
  cask "macdown"
  cask "iterm2"
  cask "steam"
  cask "eclipse-ide"
  cask "java"
  cask "alfred"

  # Unix
  brew "tmux"
EOF

echo "Checking shell version..."
case "$SHELL" in 
  */zsh) 
    echo "Already using zsh..." ;;
  *)
    echo "Changing to use zsh..."
    chsh -s "$(which zsh)" ;;
esac

echo "Checking for Prezto..."
if ! [[ -s "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
  echo "Installing Prezto..."
  git -C "./prezto/" checkout master
  git -C "./prezto/" pull
  git -C "./prezto/" submodule update --init --recursive
  cp -a ./prezto/ "${ZDOTDIR:-$HOME}/.zprezto"

  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/*; do
    if [ $rcfile != "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/README.md ]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.$(cut -d'/' -f6 <<<"$rcfile")"
    fi
  done
fi

echo "Checking for Vundle..."
if ! [[ -s "${ZDOTDIR:-$HOME}/.vim/bundle/Vundle.vim" ]]; then
  echo "Installing Vundle..."
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo "Installing/Updating .vimrc..."
cp -a ./Vundle/.vimrc "${ZDOTDIR:-$HOME}/.vimrc"
vim +PluginInstall +qall

echo "Updating git configuration..."
git config --global core.editor "vim"

echo "Restart your shell to see changes..."
