#!/bin/sh

if ! command -v brew >/dev/null; then
  echo "Installing homebrew..."

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Updating homebrew..."
brew update

echo "Installing brew / cask applications..."
brew bundle --file=- <<EOF
  # Taps
  tap "caskroom/cask"

  # Casks
  cask "spectacle"
  cask "macdown"
  cask "iterm2"

  # Unix
  brew "tmux"
EOF

echo "Checking shell version..."
case "$SHELL" in 
  */zsh) 
    echo "Already using zsh..." ;;
  *)
    echo "Changing to use zsh..."
    chsh -s "$(which zsh)" ;;
esac
  
