#!/bin/sh

if ! command -v brew >/dev/null; then
  echo "Installing homebrew..."

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Updating homebrew..."
brew update

echo "Installing brew / cask applications..."
brew bundle --file=- <<EOF
  # Taps
  tap "caskroom/cask"

  # Casks
  cask "spectacle"
  cask "macdown"
  cask "iterm2"
  cask "steam"
  cask "eclipse-ide"
  cask "java"

  # Unix
  brew "tmux"
EOF

echo "Checking shell version..."
case "$SHELL" in 
  */zsh) 
    echo "Already using zsh..." ;;
  *)
    echo "Changing to use zsh..."
    chsh -s "$(which zsh)" ;;
esac

echo "Checking for Prezto..."
if ! [[ -s "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
  echo "Installing Prezto..."
  git -C "./zprezto/" checkout master
  git -C "./zprezto/" pull
  git -C "./zprezto/" submodule update --init --recursive
  cp -a ./prezto/ "${ZDOTDIR:-$HOME}/.zprezto"

  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/*; do
    if [ $rcfile != "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/README.md ]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.$(cut -d'/' -f6 <<<"$rcfile")"
    fi
  done
fi

echo "Restart your shell to see changes..."
